server:
  port: 8787

spring:
  datasource:
    url: jdbc:mysql://121.5.110.15:3306/qq_bot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: huang8826050
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    druid数据库连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
    initial-size: 20
    min-idle: 10
    max-active: 100

mybatis-plus:
  configuration:
    log-impl:
      org.apache.ibatis.logging.stdout.StdOutImpl

simbot:
  core:
    bots: 2027141680:huang8826050 #账号和密码
    scan-package: com.monsters.qqbot.listener
  component:
    mirai:
      heartbeat-period-millis: 60000
      heartbeat-timeout-millis: 5000
      first-reconnect-delay-millis: 5000
      reconnect-period-millis: 5000
      reconnection-retry-times: 2147483647
      protocol: ANDROID_PHONE
      no-bot-log: false
      no-network-log: false
      use-simbot-bot-log: true
      use-simbot-network-log: true
      device-info-seed: 1
      cache-type: FILE。
      login-solver-type: DEFAULT
