server:
  port: 8787

spring:
  datasource:
    url: jdbc:mysql://121.5.110.15:3306/qqbot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: huang8826050
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    druid????????
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
    initial-size: 20
    min-idle: 10
    max-active: 100

mybatis-plus:
  configuration:
    log-impl:
      org.apache.ibatis.logging.stdout.StdOutImpl
