spring:
  datasource:
    url: jdbc:mysql://121.5.110.15:6003/qqbot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: huang8826050
    driver-class-name: com.mysql.cj.jdbc.Driver

    type: com.alibaba.druid.pool.DruidDataSource
    druid:
    initial-size: 20
    min-idle: 10
    max-active: 100

mybatis-plus:
  configuration:
    log-impl:
      org.apache.ibatis.logging.stdout.StdOutImpl

simbot:
  core:
    scan-package: com.monsters.qqbot.listener
  component:
    mirai:
      heartbeat-period-millis: 60000
      heartbeat-timeout-millis: 5000
      reconnection-retry-times: 2147483647
      protocol: ANDROID_PHONE
      no-bot-log: false
      no-network-log: true
      use-simbot-bot-log: true
      use-simbot-network-log: true
      device-info-seed: 1
      cache-type: FILE?
      login-solver-type: DEFAULT
